export const RESTAURANTS_INITIAL_PLACES_API_PARAMS = {
  MaxRestaurantsPerPage: 15,
  StartFromRestaurant: 0,
};

export const NUMBER_OF_MEALS_TO_SHOW = 9;

export const GALLERY = {
  NUMBER_OF_ROWS_TO_SHOW: 1,
  NUMBER_OF_IMAGES_PER_ROW: 7,
  NUMBER_OF_IMAGES_IN_FIRST_AND_THIRD_COLUMN: 1,
  NUMBER_OF_IMAGES_IN_SECOND_COLUMN: 2,
  NUMBER_OF_IMAGES_IN_FOURTH_COLUMN: 3,
};

export const DEFAULT_MAP_VALUES = {
  CENTER: {
    lng: 33.5138,
    lat: 36.2765,
  },
  ZOOM: 14,
};
